### ISSUE TITLE
Object true has no method 'trim'

### ISSUE THREAD

**Issue by chrisdarroch** [hegemonic/jsdoc-baseline#138]
I'm getting this error when I use the jsdoc-baseline template for my code:

```
TypeError: Object true has no method 'trim'
    at exports.replaceInlineTags (/<<build_dir>>/node_modules/jsdoc/lib/jsdoc/tag/inline.js:108:27)
    at Object.exports.resolveLinks (/<<build_dir>>/node_modules/jsdoc/lib/jsdoc/util/templateHelper.js:543:12)
    at link (/<<build_dir>>/node_modules/jsdoc-baseline/lib/helpers/expression/index.js:482:35)
    at Object.eval (eval at <anonymous> (/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:172:23), <anonymous>:6:84)
    at Object.prog [as fn] (/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/dist/cjs/handlebars/runtime.js:169:15)
    at null.<anonymous> (/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/dist/cjs/handlebars/base.js:168:22)
    at Object.eval (eval at <anonymous> (/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:172:23), <anonymous>:3:26)
    at ret (/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/dist/cjs/handlebars/runtime.js:138:30)
    at ret (/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:423:21)
    at helpers.extend (/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars-layouts/index.js:94:11)
```

Seemingly most doc pages get generated except for the index.html page. I'm not sure if there are other pages that aren't generated; that's the most obvious.

I haven't narrowed down the culprit in my source yet, sorry. I'll see what I can find and try to come up with the exact docs that cause this.

This error doesn't seem to occur with the default template.

**Comment by hegemonic** [comment]
Thanks for the heads up. I have a theory about what might be causing this error, but if you can find an example from your source, that would be super-helpful.

**Comment by hegemonic** [comment]
@chrisdarroch My theory didn't pan out, so I could really use your help providing an example that triggers this error.

You should be able to narrow it down to a specific source file by running JSDoc with the `--debug` option, then finding the last line of output similar to `DEBUG: Rendering template output for module-foo.html with view symbol`. (In that example, the `foo` module would have caused the crash.)

**Comment by chrisdarroch** [comment]
I've found the culprit: a combination of `@constructor` and `@deprecated` seems to do it. Here's the reduced code sample that will reproduce it:

```
/**
 * Creates a dropdown list from a JSON object
 *
 * @constructor Dropdown
 * @deprecated
 */
Dropdown = function() {

    return {

    };

}();
```

This fragment goes through the default template just fine.

**Comment by hegemonic** [comment]
@chrisdarroch Thanks! I'll investigate.

**Comment by hegemonic** [comment]
Looks like the culprit was the `@deprecated` tag with no text. (This is perfectly legal, but Baseline wasn't handling this case correctly.)

The issue should now be fixed on master.

**Comment by chrisdarroch** [comment]
Awesome, thanks for finding and fixing it so quickly! :D
